@startuml
participant bubbleSort as Foo
participant iterator  as Foo1
participant larger  as Foo2
participant swap as Foo3

group#lightgreen happy flow
Foo -> Foo1 : [...]
Foo1 -> Foo2 : a1,a2
Foo1 <-- Foo2 : a2
end


group#pink case 1
Foo -> Foo1 : [...]
Foo1 -> Foo2 : a1,a2
Foo1 <-- Foo2 : a1
Foo1 -> Foo3 : a1,a2
Foo1 <-- Foo3 : a2,a1
end


@enduml
