@startmindmap

* Invoice
** dependency
***_ web
***_ netflix-eureka-client
***_ cloud-version
***_ data-jpa
***_ mysql-connector

** main class
***_ @EnableDiscoveryClient

** Bean
***_ RestTemplate
****_ @LoadBalanced


** application.properties
***_ db config
***_ port=8080
***_ application.name=INVOICE-SERVICE
***_ fetch-registry=true
***_ eureka.defaultZone=http://localhost:8761/eureka/
***_ hostname=localhost

** JpaRepository
***_ invoice

** Entity
***_ invoice
****_ id
****_ prodName
****_ price

** RestController
***_ post
****_ invoice
*****_ consume other api
*****_ save invoice to db




@endmindmap
