@startuml
participant heapSort as 0
participant inserter as 1
participant TopMoverHeaper  as 2
participant swapper  as 3

group#lightgreen happy flow
0->1:[a0,..,a4], a5
0<--1:[a0,..,a4, a5]
0->2:a5
2->3:a4,a5
2<--3:a4,a5
0<--2:[a0,..,a5,..,a4]
end


@enduml
