

== Aspect Oriented Programming

=== LoggingAspect.java

[source,java]
----
package base.aspect;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;

@Aspect
public class LoggingAspect {

    @Before("execution(* base.service.impl.ProductServiceImpl.multiply(..))")
    public void logBefore(JoinPoint joinPoint) {
        System.out.println("logBefore()");
    }

    @After("execution(* base.service.impl.ProductServiceImpl.multiply(..))")
    public void logAfter(JoinPoint joinPoint) {
        System.out.println("logAfter()");
    }
}
package base.main;

import base.service.ProductService;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Driver {
    public static void main(String[] args) {
        ClassPathXmlApplicationContext classPathXmlApplicationContext = new ClassPathXmlApplicationContext("config.xml");
        ProductService productService = (ProductService) classPathXmlApplicationContext.getBean("productServiceImpl");

        System.out.println(productService.multiply(2,3));

    }
}
----

=== Service.java

[source,java]
----
package base.service;

public interface ProductService {
    int multiply(int num1, int num2);
}

package base.service.impl;

import base.service.ProductService;

public class ProductServiceImpl implements ProductService {
    @Override
    public int multiply(int num1, int num2) {
        return num1 * num2;
    }
}
----

=== pom.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>spring-aop</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>spring-aop</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <springframework.version>4.3.6.RELEASE</springframework.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-aop</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjrt</artifactId>
      <version>1.6.11</version>
    </dependency>
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjweaver</artifactId>
      <version>1.6.11</version>
    </dependency>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.2</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
----

=== config.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:aop="http://www.springframework.org/schema/aop"

       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.springframework.org/schema/aop
    http://www.springframework.org/schema/aop/spring-aop.xsd">

    <aop:aspectj-autoproxy />

    <bean class="base.service.impl.ProductServiceImpl" name="productServiceImpl" />

    <bean class="base.aspect.LoggingAspect" name="loggingAspect" />

</beans>
----

== Constructor

=== POJO

....
Employee
    int id
    String name
....

=== c schema

....
xmlns:c="http://www.springframework.org/schema/c"
<bean class="com.spring.constructor.Employee" name="employee" c:id="20" c:name="saksham" />
....

....
<bean id = "onlineBakery" class = "com.upgrad.course.bakery.OnlineBakery">
    <constructor-arg ref = "cakeInventory"/>
    <property name = "breadInventory" ref = "breadInventory"/>
</bean>
....

=== constructor-arg tag

[source,xml]
----
<bean class="com.spring.constructor.Employee" name="employee">
    <constructor-arg>
        <value>20</value>
    </constructor-arg>
    <constructor-arg>
        <value>saksham</value>
    </constructor-arg>
</bean>

<!-- OR -->
<bean class="com.spring.constructor.Employee" name="employee">
    <constructor-arg value="20" />
    <constructor-arg value="saksham" />
</bean>
----

== Passing int value in method but spring taking as String

=== POJO

[source,java]
----
public class Addition {
    public Addition(int a, int b) {
        System.out.println("int");
    }
    public Addition(double a, double b) {
        System.out.println("double");
    }
    // default is string
    public Addition(String a, String b) {
        System.out.println("string");
    }
}
----

=== config.xml

[source,xml]
----
<bean class="com.spring.ambuigity.Addition" name="addition" >
    <constructor-arg value="10" />
    <constructor-arg value="20" />
</bean>
----

=== Output

....
string
....

=== Solution

....
<constructor-arg value="10" type="int" />
<constructor-arg value="20" type="int" />

Now the output will be int
....

== Insert order of setting values is not followed

=== POJO

[source,java]
----
public class Addition {

    public Addition(int a, double b) {
        System.out.println("int double");
        System.out.println("a = " + a + " b = " + b);
    }

}
----

=== config.xml

[source,xml]
----
<bean class="com.spring.ambuigity.Addition" name="addition" >
    <!-- first parameter -->
    <constructor-arg value="10.56" type="double" /> 

    <!-- second parameter -->
    <constructor-arg value="20" type="int" />
</bean>
----

=== Output

....
int double
a = 20 b = 10.56
....

=== Solution

....
<constructor-arg value="10.56" type="double" index="0"/>
<constructor-arg value="20" type="int" index="1"/>

It is make suring insertion order is preserved thats why error
Unsatisfied dependency expressed through constructor parameter 0: Ambiguous argument values for parameter of type [int]
....

'''''

== pom.xml

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.spring</groupId>
  <artifactId>core</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>core</name>
  <url>http://maven.apache.org</url>

 <properties>
        <springframework.version>4.3.6.RELEASE</springframework.version>
    </properties>
 
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${springframework.version}</version>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.2</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>

----

== config.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">


</beans>
----

== Note

....
In intelliJ the config.xml is in res folder

In eclipse

if config is in src/java/main
    path = config.xml
else 
    path = com/spring/.. /config.xml
....

'''''

== Hibernate MVC

== UserController.java

[source,java]
----
package base.controller;

import base.model.pojo.User;
import base.model.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
public class UserController {
    @Autowired
    UserService userService;

    public UserService getUserService() {
        return userService;
    }

    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    @RequestMapping("/req1")
    public String req1() {
        return "page1";
    }

    @RequestMapping("/loadAll")
    public String loadAll(ModelMap modelMap) {
        List<User> users = userService.loadAll();
        modelMap.addAttribute("users", users);
        return "page3";
    }

    @RequestMapping(value = "/req2", method = RequestMethod.POST)
    public String req2(@ModelAttribute("user") User user, ModelMap modelMap) {
        int id = userService.insert(user);
        modelMap.addAttribute("id", id);
        return "page1";
    }

    @RequestMapping("/req4")
    public @ResponseBody String req4(@RequestParam("id") int id) {
        User user = userService.findUser(id);
        String msg = "";
        if(user != null) msg = "already exist";
        return msg;
    }
}
----

== UserDao.java

[source,java]
----
package base.model.dao;

import base.model.pojo.User;

import java.util.List;

public interface UserDao {
    int insert(User user);
    List<User> loadAll();
    User findUser(Integer id);
}
----

== UserDaoImpl.java

[source,java]
----
package base.model.daoimpl;

import base.model.dao.UserDao;
import base.model.pojo.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.hibernate5.HibernateTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public class UserDaoImpl implements UserDao {

    @Autowired
    private HibernateTemplate hibernateTemplate;

    public HibernateTemplate getHibernateTemplate() {
        return hibernateTemplate;
    }

    public void setHibernateTemplate(HibernateTemplate hibernateTemplate) {
        this.hibernateTemplate = hibernateTemplate;
    }

    @Override
    public int insert(User user) {
        int result = (int) hibernateTemplate.save(user);
        return result;
    }

    @Override
    public List<User> loadAll() {
        return hibernateTemplate.loadAll(User.class);

    }

    @Override
    public User findUser(Integer id) {
        return hibernateTemplate.get(User.class, id);
    }
}
----

== User

[source,java]
----
package base.model.pojo;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class User implements Comparable<User>{

    @Id
    private Integer id;
    private String name;
    private String email;

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                '}';
    }


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public int compareTo(User user) {
        return this.name.compareTo(user.name);
    }
}
----

== UserService.java

[source,java]
----
package base.model.service;

import base.model.pojo.User;

import java.util.List;

public interface UserService {
    int insert(User user);
    List<User> loadAll();
    User findUser(Integer id);
}
----

== UserServiceImpl.java

[source,java]
----
package base.model.serviceImpl;

import base.model.dao.UserDao;
import base.model.pojo.User;
import base.model.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Collection;
import java.util.Collections;
import java.util.List;

@Service
public class UserServiceImpl implements UserService {
    @Autowired
    private UserDao userDao;

    public UserDao getUserDao() {
        return userDao;
    }

    public void setUserDao(UserDao userDao) {
        this.userDao = userDao;
    }

    @Override
    @Transactional
    public int insert(User user) {
        return userDao.insert(user);
    }

    @Override
    public List<User> loadAll() {
        List<User> users = userDao.loadAll();
        Collections.sort(users);
        return users;
    }

    @Override
    public User findUser(Integer id) {
        return userDao.findUser(id);
    }
}
----

== pom.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>spring-mvc-hibernate</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>war</packaging>

  <name>spring-mvc-hibernate Maven Webapp</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>
  <properties>
    <springframework.version>4.3.6.RELEASE</springframework.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-orm</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>5.2.17.Final</version>
    </dependency>
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>8.0.13</version>
    </dependency>
    <dependency>
      <groupId>jstl</groupId>
      <artifactId>jstl</artifactId>
      <version>1.2</version>
    </dependency>
    <dependency>
      <groupId>taglibs</groupId>
      <artifactId>standard</artifactId>
      <version>1.1.2</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- see http://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_war_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-war-plugin</artifactId>
          <version>3.2.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.2</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.tomcat.maven</groupId>
          <artifactId>tomcat7-maven-plugin</artifactId>
          <version>2.2</version>
          <configuration>
            <port>9090</port>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
----

== config.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.springframework.org/schema/tx
    http://www.springframework.org/schema/tx/spring-tx.xsd">

    <tx:annotation-driven/>

    <context:component-scan base-package="base" />

    <bean class="org.springframework.jdbc.datasource.DriverManagerDataSource" name="dataSource">
        <property name="driverClassName">
            <value>com.mysql.cj.jdbc.Driver</value>
        </property>

        <property name="url">
            <value>jdbc:mysql://localhost/mydb</value>
        </property>

        <property name="username">
            <value>root</value>
        </property>

        <property name="password">
            <value>root</value>
        </property>
    </bean>

    <bean class="org.springframework.orm.hibernate5.LocalSessionFactoryBean" name="localSessionFactoryBean">
        <property name="dataSource">
            <ref bean="dataSource"/>
        </property>
        <property name="hibernateProperties">
            <props>
                <prop key="hibernate.dialect">org.hibernate.dialect.MySQLDialect</prop>
                <prop key="hibernate.show_sql">true</prop>
            </props>
        </property>
        <property name="annotatedClasses">
            <list>
                <value>base.model.pojo.User</value>
            </list>
        </property>
    </bean>

    <bean class="org.springframework.orm.hibernate5.HibernateTemplate" name="hibernateTemplate">
        <property name="sessionFactory">
            <ref bean="localSessionFactoryBean"/>
        </property>
    </bean>

    <bean class="org.springframework.orm.hibernate5.HibernateTransactionManager" name="transactionManager">
        <property name="sessionFactory">
            <ref bean="localSessionFactoryBean"/>
        </property>
    </bean>

    <bean class="org.springframework.web.servlet.view.InternalResourceViewResolver" name="internalResourceViewResolver">
        <property name="prefix">
            <value>/WEB-INF/view/</value>
        </property>
        <property name="suffix">
            <value>.jsp</value>
        </property>

    </bean>
</beans>
----

== web app xml

[source,xml]
----
<!DOCTYPE web-app PUBLIC
        "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
        "http://java.sun.com/dtd/web-app_2_3.dtd" >
<web-app>

  <display-name>Archetype Created Web Application</display-name>

  <servlet>
    <servlet-name>front</servlet-name>
    <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
  </servlet>

  <servlet-mapping>
    <servlet-name>front</servlet-name>
    <url-pattern>/</url-pattern>
  </servlet-mapping>

</web-app>
----

....
web-app
    display-name
    servlet
        name
        class
    mapping
        name
        url-pattern
....

== ajax page .jsp

[source,html]
----
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page isELIgnored="false" %>
<html>
   <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script>
            $(document).ready(() => {
                $("#id1").change(() => {
                    $.ajax({
                        url: "req4",
                        data: {id: $("#id1").val()},
                        success: function(response) {
                            $("#errorMessage").text(response);
                        }
                    });
                });
            });
        </script>
   </head>
   <body>
        <form action="req2" method="post">
            <input type="text" name="id" id="id1"/>
            <span id="errorMessage"></span><br/>
            <input type="text" name="name" />
            <input type="text" name="email" />
            <button type="submit">Submit</button>
        </form>
        ${id}
   </body>
</html>
----

== for each page .jsp

[source,html]
----
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page isELIgnored="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
   <body>
        <c:forEach items="${users}" var="user">
            ${user.id}
            ${user.name}
            ${user.email}<br/>
        </c:forEach>
   </body>
</html>
----

== Run

mvn clean install

mvn tomcat7:run

== Database

use mydb;

create table user(id int primary key,name varchar(20),email
varchar(30));

drop table user;

select * from user;

=== Product

....
@Entity
Product
    @Id
    int id;
    String name;
    String description;
    double price;
....

=== ProductDao

[source,java]
----
public interface ProductDao {
    int insert(Product product);
    void update(Product product);
    void delete(Product product);
    Product select(int id);
    List<Product> selectAll();
}
----

=== ProductDaoImpl

[source,java]
----
@Component
public class ProductDaoImpl implements ProductDao {

    @Autowired
    HibernateTemplate hibernateTemplate;

    @Override
    @Transactional
    public int insert(Product product) {
        Serializable save = hibernateTemplate.save(product);
        return (int) save;
    }

    @Override
    @Transactional
    public void update(Product product) {
        hibernateTemplate.update(product);
    }

    @Override
    @Transactional
    public void delete(Product product) {
        hibernateTemplate.delete(product);
    }

    @Override
    public Product select(int id) {
        Product product = hibernateTemplate.get(Product.class, id);
        return product;
    }

    @Override
    public List<Product> selectAll() {
        List<Product> products = hibernateTemplate.loadAll(Product.class);
        return products;
    }
}
----

=== ProductDriver

[source,java]
----
public class ProductDriver {
    public static void main(String[] args) {
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("config.xml");
        ProductDao productDao = (ProductDao) applicationContext.getBean("productDaoImpl");
        Product product = new Product();
        product.setId(2);
        product.setName("asus");
        product.setDescription("nice");
        product.setPrice(15.23);
//        Product select = productDao.select(1);
//        System.out.println(select);
        List<Product> products = productDao.selectAll();
        System.out.println(products);

    }
}
----

=== Database

use springHibernateTemplate;

create table product(id int primary key,name varchar(20),description
varchar(100),price decimal(8,3));

select * from product;

=== pom.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>spring-orm</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>spring-orm Maven Webapp</name>
    <!-- FIXME change it to the project's website -->
    <url>http://www.example.com</url>

    <properties>
        <springframework.version>4.3.6.RELEASE</springframework.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.2.5.Final</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.13</version>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.2</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
----

=== config.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.springframework.org/schema/tx
    http://www.springframework.org/schema/tx/spring-tx.xsd">

    <tx:annotation-driven/>

    <context:component-scan base-package="daoimpl"/>

    <bean class="org.springframework.jdbc.datasource.DriverManagerDataSource" name="dataSource">
        <property name="driverClassName">
            <value>com.mysql.cj.jdbc.Driver</value>
        </property>

        <property name="url">
            <value>jdbc:mysql://localhost/mydb</value>
        </property>

        <property name="username">
            <value>root</value>
        </property>

        <property name="password">
            <value>root</value>
        </property>
    </bean>

    <bean class="org.springframework.orm.hibernate5.LocalSessionFactoryBean" name="localSessionFactoryBean">
        <property name="dataSource">
            <ref bean="dataSource"/>
        </property>
        <property name="hibernateProperties">
            <props>
                <prop key="hibernate.dialect">org.hibernate.dialect.MySQLDialect</prop>
                <prop key="hibernate.show_sql">true</prop>
            </props>
        </property>
        <property name="annotatedClasses">
            <list>
                <value>pojo.Product</value>
                <value>pojo.Passenger</value>
            </list>
        </property>
    </bean>

    <bean class="org.springframework.orm.hibernate5.HibernateTemplate" name="hibernateTemplate">
        <property name="sessionFactory">
            <ref bean="localSessionFactoryBean"/>
        </property>
    </bean>

    <bean class="org.springframework.orm.hibernate5.HibernateTransactionManager" name="transactionManager">
        <property name="sessionFactory">
            <ref bean="localSessionFactoryBean"/>
        </property>
    </bean>


</beans>
----

== innerBean

....
Address 
    int hno
    String street
    String city


Employee 
    int id
    Address address
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.innerbean.Employee" name="employee" p:id="10" >
        <property name="address">
            <bean class="com.spring.innerbean.Address" p:hno="12" p:street="silicon valley" p:city="mumbai" />
        </property>
    </bean>
    
</beans>
....

....
public class Test {
    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/innerbean/config.xml");
        Employee employee = (Employee) applicationContext.getBean("employee");
        
        System.out.println(employee.toString());

    }
}
....

....
Employee [id=10, address=Address [hno=12, street=silicon valley, city=mumbai]]
....

....
package org.example;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class DaoConfig {

    @Bean
    public Dao dao() {
        return new Dao();
    }

}
....

....
package org.example;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

@Configuration
@Import(DaoConfig.class)
public class SpringConfig {

    @Bean
    public Service service() {
        return new Service();
    }

}
....

....
package org.example;

import org.springframework.stereotype.Component;

@Component
public class Dao {
    public void create() {
        System.out.println("create()");
    }
}
....

....
package org.example;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class Service {

    @Autowired
    Dao dao;

    public void save() {
        dao.create();
    }
}
....

....
package org.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Driver {
    public static void main(String[] args) {
        ApplicationContext applicationContext = new AnnotationConfigApplicationContext(SpringConfig.class);
//        Dao dao = applicationContext.getBean(Dao.class);
        Service service = applicationContext.getBean(Service.class);

        service.save();
//        dao.create();

    }
}
....

....
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>spring-java-config</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>spring-java-config</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>
  <properties>
    <springframework.version>4.3.6.RELEASE</springframework.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${springframework.version}</version>
    </dependency>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.2</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
....

== Spring JDBC

[source,java]
----
public class EmployeeDriver {
    public static void main(String[] args) {
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("config.xml");
        EmployeeDao employeeDao = (EmployeeDao) applicationContext.getBean("employeeDaoImpl");
        Employee employee = new Employee();
        employee.setId(1);
        employee.setFirstName("caring mummy");
        employee.setLastName("sangal");
        List<Employee> employeeList = employeeDao.selectAll();
        System.out.println(employeeList);
    }
}



public class EmployeeRowMapper implements RowMapper {
    @Override
    public Employee mapRow(ResultSet rs, int rowNum) throws SQLException {
        Employee employee = new Employee();
        employee.setId(rs.getInt(1));
        employee.setFirstName(rs.getString(2));
        employee.setLastName(rs.getString(3));
        return employee;
    }
}


@Component
public class EmployeeDaoImpl implements EmployeeDao {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    public JdbcTemplate getJdbcTemplate() {
        return jdbcTemplate;
    }

    public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public int insert(Employee employee) {
        String sql = "insert into employee values(?, ?, ?)";
        int result = jdbcTemplate.update(sql, employee.getId(), employee.getFirstName(), employee.getLastName());
        return result;
    }

    @Override
    public int update(Employee employee) {
        String sql = "update employee set firstName=?, lastName=? where id=?";
        int result = jdbcTemplate.update(sql, employee.getFirstName(), employee.getLastName(), employee.getId());
        return result;
    }

    @Override
    public int delete(int id) {
        String sql = "delete from employee where id=?";
        int result = jdbcTemplate.update(sql, id);
        return result;
    }

    @Override
    public Employee select(int id) {
        String sql = "select * from employee where id=?";
        EmployeeRowMapper employeeRowMapper = new EmployeeRowMapper();
        Employee employee = (Employee) jdbcTemplate.queryForObject(sql, employeeRowMapper, id);
        return employee;
    }

    @Override
    public List<Employee> selectAll() {
        String sql = "select * from employee";
        EmployeeRowMapper employeeRowMapper = new EmployeeRowMapper();
        List<Employee> employeeList= (List<Employee>) jdbcTemplate.query(sql, employeeRowMapper);
        return employeeList;
    }
}



public interface EmployeeDao {
    int insert(Employee employee);
    int update(Employee employee);
    int delete(int id);
    Employee select(int id);
    List<Employee> selectAll();
}
----

....
Employee 
    int id;
    String firstName;
    String lastName;
....

=== Database

use mydb;

create table passenger(id int,firstname varchar(20),lastname
varchar(20));

select * from passenger;

drop table passenger;

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.saksham</groupId>
    <artifactId>spring-jdbc-template</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>spring-mvc Maven Webapp</name>
    <!-- FIXME change it to the project's website -->
    <url>http://www.example.com</url>


    <properties>
        <springframework.version>4.3.6.RELEASE</springframework.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${springframework.version}</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.13</version>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.2</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
----

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
       xmlns:p="http://www.springframework.org/schema/p"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <context:component-scan base-package="daoImpl" />
    <bean class="org.springframework.jdbc.datasource.DriverManagerDataSource" name="dataSource">
        <property name="driverClassName">
            <value>com.mysql.cj.jdbc.Driver</value>
        </property>

        <property name="url">
            <value>jdbc:mysql://localhost/mydb</value>
        </property>

        <property name="username">
            <value>root</value>
        </property>
        
        <property name="password">
            <value>root</value>
        </property>
    </bean>

    <bean class="org.springframework.jdbc.core.JdbcTemplate" name="jdbcTemplate">
        <property name="dataSource">
            <ref bean="dataSource" />
        </property>
    </bean>

<!--    <bean class="daoImpl.EmployeeDaoImpl" name="employeeDaoImpl">-->
<!--        <property name="jdbcTemplate">-->
<!--            <ref bean="jdbcTemplate" />-->
<!--        </property>-->
<!--    </bean>-->


</beans>
----

== Packages

The prefix of a unique package name is always written in all-lowercase
ASCII letters and should be one of the top-level domain names, currently
com, edu, gov, mil, net, org, or one of the English two-letter codes
identifying countries as specified in ISO Standard 3166, 1981.
Subsequent components of the package name vary according to an
organization’s own internal naming conventions. Such conventions might
specify that certain directory name components be division, department,
project, machine, or login names.

From
https://stackoverflow.com/questions/3179216/what-is-the-convention-for-word-separator-in-java-package-names

• com.sun.sunsoft.DOE • gov.whitehouse.socks.mousefinder •
com.JavaSoft.jag.Oak • org.npr.pledge.driver • uk.ac.city.rugby.game

From
https://stackoverflow.com/questions/3179216/what-is-the-convention-for-word-separator-in-java-package-names

== Setter method

setGender = `<property name="gender">`

=== Primitive field POJO

....
Employee
    int id
    String name
....

==== Using value as tag and attribute

[source,xml]
----
<bean 
    class="com.spring.primitive.Employee" 
    name="employee">

    <!-- value as tag -->
    <property name="id">
        <value>20</value>
    </property>
    
    <!-- value as attribute -->
    <property 
        name="name" 
        value="saksham"/> 

</bean>
----

==== Using p schema

[source,xml]
----
<bean 
    class="com.spring.primitive.Employee" 
    name="employee" 
    p:id="20" 
    p:name="saksham"/>
----

=== List field POJO

....
Hospital 
    String name
    List<String> departments
....

[source,xml]
----
<property name="departments">
    <!-- empty list -->
    <list /> 
</property>
    
<property name="departments">
    <!-- single element -->
    <value>1</value>
</property>

<property name="departments">
    <list>
        <value>1</value>
        <value>2</value>
        <value>3</value>
    </list>
</property>
----

=== Map field POJO

....
Customer
    int id;
    Map<Integer, String> products;
....

[source,xml]
----
<property name="products">
    <map>
        <entry key="100" value="asus"></entry>
        <entry key="200">
            <value>moto</value>
        </entry>
        <entry value="mi">
            <key>
                <value>300</value>
            </key>
        </entry>
        <entry>
            <key>
                <value>400</value>
            </key>
            <value>iphone</value>
        </entry>
    </map>
</property>
----

=== Properties field POJO

....
Language 
    Properties countryAndLanguage
....

[source,xml]
----
<property name="countryAndLanguage">
    <props>
        <prop key="India">Hindi</prop>
        <prop key="USA">English</prop>
    </props>
</property>
----

=== Reference field POJO

....
Score
    Double maths
    Double physics
    Double chemistry


Student
    Score score
....

[source,xml]
----
<bean class="com.spring.reference.Score" name="score" p:maths="67" p:physics="78" p:chemistry="89"/>

<bean class="com.spring.reference.Student" name="student">

    <property name="score">
        <ref bean="score"/>
    </property>
</bean>

<!-- OR -->
<bean class="com.spring.reference.Student" name="student">  
    <property name="score" ref="score" />
</bean>

<!-- OR -->
<bean class="com.spring.reference.Student" name="student" p:score-ref="score" />
----

=== Set field POJO

....
CarDealer
    String name
    Set<String> models
....

[source,xml]
----
<property name="models">
    <set>
        <value>1</value>
        <value>2</value>
        <value>3</value>
    </set>
</property>
----

'''''

== What is spring?

Used to separate POJO creation from project.

== Merits

Develop can focus on business logic instead of object creation

== Request flow

controller / service / dao / database

== How spring is able to create object separately?

Spring use `<bean>` or @Component to do this

She can fill the object in two ways:

* setter method
* constructor

'''''

== Standalone

....
ProductList 
    List<String> productNames
....

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xmlns:util="http://www.springframework.org/schema/util"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.springframework.org/schema/util
    http://www.springframework.org/schema/util/spring-util.xsd">

    <util:list list-class="java.util.LinkedList" id="productNames">
        <value>macbook</value>
        <value>iphone</value>
    </util:list>
    
    
    <bean class="com.spring.standalone.ProductList" name="productList" p:productNames-ref="productNames" />
        
</beans>
----

[source,java]
----
public class Test {
    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/standalone/config.xml");
        ProductList productList = (ProductList) applicationContext.getBean("productList");
        
        // because search by type, therefore there is error
        System.out.println(productList);

    }
}
----

=== Output

....
ProductList [productNames=[macbook, iphone]]
....

=== JSP template in servlet

....
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@page isELIgnored="false" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/css/styles.css">
</head>
<body>



</body>
</html>
....

=== scriptlets

....
<%!   
 // java code 
%>  

<%= // direct print %>  

<% out.print("Today is:"+java.util.Calendar.getInstance().getTime()); %>  

<%   
  // used for writing servlet code.
%>  
....

=== for loop in JSP using JSTL

....
<table>
    <tr>
        <th>Airlines</th>
        <th>Departure City</th>
        <th>Arrival City</th>
        <th>Departure Time</th>

    </tr>

    <c:forEach items="${flights}" var="flight">
        <tr>
            <td>${flight.operatingAirlines}</td>
            <td>${flight.departureCity}</td>
            <td>${flight.arrivalCity}</td>
            <td>${flight.estimatedDepartureTime}</td>
            <td><a href="showCompleteReservation?flightId=${flight.id}">Select</a></td>
        </tr>

    </c:forEach>
</table>
....

....
${msg} // direct print variable in jsp

request.getContextPath() // return root directory of project
....

=== If user is not logged in then redirect him to default page i.e. index.jsp

....
try {
    if (session.getAttribute("emailId").equals(null)) {
        response.sendRedirect(request.getContextPath());
    }
} catch (NullPointerException e) {
    response.sendRedirect(request.getContextPath());
}
....

=== Logged In as

....
Logged In as <%
try {
    out.print(session.getAttribute("emailId").toString().split("@")[0]);
} catch (NullPointerException e) {}
%>
....

....
<form id="post_form" method="post" action="<%=request.getContextPath()%>/blog/post">
<span><%=session.getAttribute("emailId")%></span>
....

=== @WebServlet(``/blog/post'')

....
public class PostServlet extends HttpServlet 
....

=== log out

....
<%
    session.invalidate();
    response.sendRedirect(request.getContextPath());
%>
....

=== Write java code to populate all the tag options in the drop-down menu.

....
<%
    HashSet<String> tagList = new DAOFactory().getPostCRUDS().findAllTags();
    Object[] array = tagList.toArray();
    for (int i = 0; i < array.length; i++) { %>
<option value="<%=array[i]%>"><%=array[i]%>
</option>
<%
    }
%>
....

=== TODO: 7.15. Write code to get posts for the selected ``tag'' and render the search result on the web page.

....

<%
    if (request.getMethod().equals("POST")) {
        List<PostDTO> postDTOS = new DAOFactory().getPostCRUDS().findByTag(request.getParameter("tag"));
        for (int i = 0; i < postDTOS.size(); i++) { %>
            <div class="post-list">
                <div>Post Id: <%=postDTOS.get(i).getPostId()%>
                </div>
                <div>Email Id: <%=postDTOS.get(i).getEmailId()%>
                </div>
                <div>Title: <%=postDTOS.get(i).getTitle()%></div>
                <div>Tag: <%=postDTOS.get(i).getTag()%>
                </div>
                <div>Description: <%=postDTOS.get(i).getDescription()%>
                </div>
                <div>Time: <%=DateTimeFormatter.format(postDTOS.get(i).getTimestamp())%>
                </div>
            </div>
<%
        }
        if (postDTOS.size() < 1) {
            out.print("Sorry no posts exists for this tag");
        }

    }
%>
....

=== If user tries to click on browser bac k button then he/ she should not be able to access this page*/

....
response.setHeader("Cache-Control", "no-cache");
response.setHeader("Cache-Control", "no-store");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expires", 0);
....

== @Autowired

=== POJO

....
Employee
    @Autowired
    Address
....

=== config.xml

[source,xml]
----
<context:annotation-config />

<bean 
    class="com.spring.annotation.Address" 
    name="address" 
    p:hno="12" 
    p:street="silicon valley" 
    p:city="mumbai"/>   
<bean 
    class="com.spring.annotation.Employee" 
    name="employee"/>       
----

=== Autowire using constructor

==== POJO

....
Employee
    Address address
....

==== config.xml

[source,xml]
----
<bean 
    class="com.spring.autowire.Address" 
    name="address" 
    p:hno="12" 
    p:street="silicon valley" 
    p:city="mumbai" />  
<bean 
    class="com.spring.autowire.Employee" 
    name="employee" 
    autowire="constructor" />
----

=== Autowire by name

[source,xml]
----
<bean class="com.spring.autowire.Address" name="address" p:hno="12" p:street="silicon valley" p:city="mumbai" />
<bean class="com.spring.autowire.Address" name="address2" p:hno="32" p:street="silicon valley" p:city="mumbai" />
<bean class="com.spring.autowire.Employee" name="employee" autowire="byName" /> 
----

==== POJO

....
Employee
    @Autowired
    @Qualifier("a1")
    Address
....

==== config.xml

[source,xml]
----
<context:annotation-config />
<bean class="com.spring.annotation.Address" name="a1" p:hno="12" p:street="silicon valley" p:city="mumbai" />
<bean class="com.spring.annotation.Employee" name="employee" /> 
----

== @Component

=== POJO

....
// default is instructor
@Component("instructor")
Instructor
    int id
    String name
....

=== config.xml

[source,xml]
----
<context:component-scan base-package="com.spring.stereotype" /> 
----

== @Required

....
Patient

    private int id;
    private String name;
    
    @Required
    public void setId(int id) {
        this.id = id;
    }
....

'''''

____
To make mandatory attribute using @Required

@Required is applied only on setter method
____

== Patient.java

....
package com.spring.dependencycheck;

import java.util.List;

import org.springframework.beans.factory.annotation.Required;

public class Patient {

    private int id;
    private String name;
    private List<String> medicine;
    
    public int getId() {
        return id;
    }
    
    @Required
    public void setId(int id) {
        this.id = id;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public List<String> getMedicine() {
        return medicine;
    }
    
    public void setMedicine(List<String> medicine) {
        this.medicine = medicine;
    }
    
    @Override
    public String toString() {
        return "Patient [id=" + id + ", name=" + name + "]";
    }
    
}
....

== config.xml

....
<bean class="com.spring.dependencycheck.Patient" name="patient" p:id="12" />
<bean class="org.springframework.beans.factory.annotation.RequiredAnnotationBeanPostProcessor" />
....

== Test.java

....
package com.spring.dependencycheck;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {
    public static void main(String[] args) {        
        try {
            ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/dependencycheck/config.xml");
            Patient patient = (Patient) applicationContext.getBean("patient");
            System.out.println(patient);
        } catch (Exception e) {
            System.err.println("\nError: " + e.getMessage());
        }
        
    }
}
....

....
Output:
Patient [id=12, name=null]
....

....
package com.spring.autowire;

public class Employee {

    private Address address;
    
    public Address getAddress() {
        return address;
    }
    public void setAddress(Address address) {
        this.address = address;
    }
    @Override
    public String toString() {
        return "Employee [address=" + address + "]";
    }
    
    
}
....

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.autowire.Address" name="address" p:hno="12" p:street="silicon valley" p:city="mumbai" />
    
    <bean class="com.spring.autowire.Employee" name="employee" autowire="byType" /> 
    
</beans>
----

....
package com.spring.autowire;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {
    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/autowire/config.xml");
        Employee employee = (Employee) applicationContext.getBean("employee");
        
        System.out.println(employee);

    }
}
....

....
Employee [address=Address [hno=12, street=silicon valley, city=mumbai]]
....

....
// error
package com.spring.autowire;

public class Employee {

    private Address address;
    
    public Address getAddress() {
        return address;
    }
    public void setAddress(Address address) {
        this.address = address;
    }
    @Override
    public String toString() {
        return "Employee [address=" + address + "]";
    }
    
    
}
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.autowire.Address" name="address1" p:hno="12" p:street="silicon valley" p:city="mumbai" />
    <bean class="com.spring.autowire.Address" name="address2" p:hno="12" p:street="silicon valley" p:city="mumbai" />
    
    <bean class="com.spring.autowire.Employee" name="employee" autowire="byType" /> 
    
</beans>
....

....
package com.spring.autowire;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {
    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/autowire/config.xml");
        Employee employee = (Employee) applicationContext.getBean("employee");
        
        // because search by type, therefore there is error
        System.out.println(employee);

    }
}
....

____
No qualifying bean of type `com.spring.autowire.Address' available:
expected single matching bean but found 2: address1,address2
____

....
public class Patient {

    private int id;

    @PostConstruct
    public void init() {
        System.out.println("init()");
    }
    
    @PreDestroy
    public void destroy() {
        System.out.println("destroy()");
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        System.out.println("setId()");
        this.id = id;
    }
    
    @Override
    public String toString() {
        return "Patient [id=" + id + "]";
    }

}
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.annotation.Patient" name="patient" p:id="10" />
    <bean class="org.springframework.context.annotation.CommonAnnotationBeanPostProcessor" />
    
</beans>
....

....

package com.spring.annotation;

import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {

    public static void main(String[] args) {
        AbstractApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/annotation/config.xml");
        Patient patient = (Patient) applicationContext.getBean("patient");
        
        System.out.println(patient.toString());
        applicationContext.registerShutdownHook();

    }
    
    
    

}
....

....
setId()
init()
Patient [id=10]
destroy()
....

....

<bean class="com.spring.annotation.Patient" name="patient" p:id="10" />
<context:annotation-config />
....

....
package com.spring.lifecycleinterface;

import org.springframework.beans.factory.DisposableBean;
import org.springframework.beans.factory.InitializingBean;

public class Patient implements InitializingBean, DisposableBean{
    private int id;
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        System.out.println("setId()");
        this.id = id;
    }

    @Override
    public String toString() {
        return "Patient [id=" + id + "]";
    }

    @Override
    public void afterPropertiesSet() throws Exception {
        System.out.println("afterPropertiesSet()");
    }

    @Override
    public void destroy() throws Exception {
        System.out.println("destroy()");
    }

    
}
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.lifecycleinterface.Patient" name="patient" p:id="10" />
    
</beans>
....

....

package com.spring.lifecycleinterface;

import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {
    public static void main(String[] args) {
        AbstractApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/lifecycleinterface/config.xml");
        Patient patient = (Patient) applicationContext.getBean("patient");
        
        System.out.println(patient.toString());
        applicationContext.registerShutdownHook();
                
    }
}
....

....

setId()
afterPropertiesSet()
Patient [id=10]
destroy()
....

....
 package com.spring.annotation;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;

public class Patient {

    private int id;

    @PostConstruct
    public void init() {
        System.out.println("init()");
    }
    
    @PreDestroy
    public void destroy() {
        System.out.println("destroy()");
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        System.out.println("setId()");
        this.id = id;
    }
    
    @Override
    public String toString() {
        return "Patient [id=" + id + "]";
    }

}
....

....

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.annotation.Patient" name="patient" p:id="10" />
    <bean class="org.springframework.context.annotation.CommonAnnotationBeanPostProcessor" />
    
</beans>
....

....

package com.spring.annotation;

import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {

    public static void main(String[] args) {
        AbstractApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/annotation/config.xml");
        Patient patient = (Patient) applicationContext.getBean("patient");
        
        System.out.println(patient.toString());
        applicationContext.registerShutdownHook();

    }
    
    
    

}
....

....
setId()
init()
Patient [id=10]
destroy()
....

....
<bean class="com.spring.annotation.Patient" name="patient" p:id="10" />
<context:annotation-config />
....

....
package com.spring.lifecyclexml;

import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {
    public static void main(String[] args) {
        AbstractApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/lifecyclexml/config.xml");
        Patient patient = (Patient) applicationContext.getBean("patient");
        
        System.out.println(patient.toString());
        applicationContext.registerShutdownHook();
    }
}
....

....
package com.spring.lifecyclexml;

public class Patient {
    private int id;

    public void init() {
        System.out.println("init()");
    }
    
    public void destroy() {
        System.out.println("destroy()");
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        System.out.println("setId()");
        this.id = id;
    }

    @Override
    public String toString() {
        return "Patient [id=" + id + "]";
    }

}
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.lifecyclexml.Patient" name="patient" p:id="10" init-method="init" destroy-method="destroy" />
    
</beans>
....

....
Output:
setId()
init()
Patient [id=10]
destroy()
....

== externalization

....
# details
dbServer=sakshamServer
dbPort=8080
dbUser=root
dbPass=pass
....

....
package com.spring.externalization;

public class MyDAO {
    private String dbServer;

    public MyDAO(String dbServer) {
        super();
        this.dbServer = dbServer;
    }   
}
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <context:property-placeholder location="com/spring/externalization/database.properties"/>
    <bean class="com.spring.externalization.MyDAO" name="myDAO" >
        <constructor-arg value="${dbServer}" />
    </bean>
        

</beans>
....

....
package com.spring.externalization;

import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {

    public static void main(String[] args) {
        
        
        ClassPathXmlApplicationContext classPathXmlApplicationContext = new ClassPathXmlApplicationContext("com/spring/externalization/config.xml");
        MyDAO myDAO = (MyDAO) classPathXmlApplicationContext.getBean("myDAO");
        
        System.out.println(myDAO);
    
        

    }

}
....

....
MyDAO [dbServer=sakshamServer]


# prototype scope
....

package com.spring.scope;

public class Employee { private int id; private String name;

....
public int getId() {
    return id;
}
public void setId(int id) {
    this.id = id;
}
public String getName() {
    return name;
}
public void setName(String name) {
    this.name = name;
}
@Override
public String toString() {
    return "Employee [id=" + id + ", name=" + name + "]";
}
....

}

....

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.scope.Employee" name="employee" p:id="20" p:name="saksham" scope="prototype"/>

</beans>
....

....
package com.spring.scope;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Test {

    public static void main(String[] args) {
        // TODO Auto-generated method stub
        
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/scope/config.xml");
        Employee employee1 = (Employee) applicationContext.getBean("employee");
        Employee employee2 = (Employee) applicationContext.getBean("employee");
        
        System.out.println(employee1.hashCode());
        System.out.println(employee2.hashCode());

    }

}
....

....
1442045361
146611050
....

== single scope

....
Employee
    int id
    String name
....

....
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd">

    <bean class="com.spring.scope.Employee" name="employee" p:id="20" p:name="saksham" scope="singleton"/>

</beans>
....

....
public class Test {

    public static void main(String[] args) {
        // TODO Auto-generated method stub
        
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("com/spring/scope/config.xml");
        Employee employee1 = (Employee) applicationContext.getBean("employee");
        Employee employee2 = (Employee) applicationContext.getBean("employee");
        
        System.out.println(employee1.hashCode());
        System.out.println(employee2.hashCode());

    }

}
....

....
650023597
650023597
....
