@startmindmap
* API gateway
** dependency
***_ gateway
***_ netflix-eureka-client
** main class
***_ @EnableDiscoveryClient
** application.yml
***_ port=9090
***_ application.name=API-GATEWAY
***_ eureka.defaultZone=http://localhost:8761/eureka/
***_ endpoints.include=*
***_ gateway.routes

** application.properties
***_ default-filters
***_ globalcors
@endmindmap